
const Homeproduct =
[
    {
        id: 1,
        Name: 'Vinegar',
        price: '399',
        image: 'images/img1.jpg',
        cat: 'tv',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Red Chillie',
        price: '499',
        image: 'images/img6.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Vinegar',
        price: '399',
        image: 'images/img1.jpg',
        cat: 'watch',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Pickle',
        price: '699',
        image: 'images/img11.jpg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Vinegar Combo',
        price: '1299',
        image: 'images/img5.jpg',
        cat: 'speaker',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'Apple Vinegar',
        price: '450',
        image: 'images/product/gal10.jpeg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Pickle',
        price: '499',
        image: 'images/img7.jpg',
        cat: 'headphone',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'Green Chillie',
        price: '299',
        image: 'images/img8.jpg',
        cat: 'electronics',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Mango Pickle',
        price: '399',
        image: 'images/img9.jpeg',
        cat: 'phone',
        type: 'top',
    },
    {
        id: 10,
        Name: 'Vinegar Combo',
        price: '1499',
        image: 'images/gal10.jpeg',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 11,
        Name: 'Vinegar',
        price: '349',
        image: 'images/img4.jpg',
        cat: 'speaker',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Pickle',
        price: '499',
        image: 'images/img12.jpg',
        cat: 'speaker',
        type: 'top',
    },
]
export default Homeproduct;